# Generated by Django 4.0.6 on 2022-07-29 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('mbti', models.CharField(max_length=4, null=True)),
                ('keyword1', models.CharField(max_length=10, null=True)),
                ('keyword2', models.CharField(max_length=10, null=True)),
                ('keyword3', models.CharField(max_length=10, null=True)),
                ('info', models.CharField(max_length=50, null=True)),
                ('main_act', models.CharField(max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
