# Generated by Django 3.2.3 on 2022-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0004_alter_freecomment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('mbti', models.CharField(max_length=5, null=True)),
                ('meeting', models.BinaryField(editable=True, null=True)),
                ('feedback', models.BinaryField(editable=True, null=True)),
                ('ongoing', models.BinaryField(editable=True, null=True)),
                ('info', models.CharField(max_length=100, unique=True)),
                ('main_act', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
