# Generated by Django 3.2.3 on 2022-07-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feedback',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='meeting',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ongoing',
            field=models.BooleanField(null=True),
        ),
    ]
