# Generated by Django 3.2.3 on 2022-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0007_auto_20220729_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
